vuelvo a proceso.sh

diff --git a/bin/stop b/bin/stop
--- a/bin/stop
+++ b/bin/stop
@@ -1,15 +1,28 @@
 #!/bin/bash
 
-chmod +x ./glog
-
-ps cax | grep "procesoSisOp.sh" > /dev/null
-
-if [ $? -eq 0 ]; 
+if [ "$TP_SISOP_INIT" == "YES" ] #Variable que vendría de más arriba
 then
-	pkill "procesoSisOp.sh"
-	echo "============ Se invoca el comando correctamente. Se aborta la ejecución de procesoSisOp.sh ============"
-	./glog "stop" "Se invoca el comando correctamente. Se aborta la ejecución de procesoSisOp.sh"
+	ps cax | grep "proceso.sh" > /dev/null
+
+	if [ $? -eq 0 ]; 
+	then
+		pkill "proceso.sh"
+		echo "============ [STOP] Se invoca el comando correctamente. Se aborta la ejecución de proceso.sh ============"
+		"$BINDIR"/glog "stop" "Se invoca el comando correctamente. Se aborta la ejecución de proceso.sh"
+	else
+		echo "============ [STOP] [ERROR] No se puede invocar el comando ya que proceso.sh no se encuentra en ejecución ============"
+		"$BINDIR"/glog "stop" "No se pudo invocar el comando ya que proceso.sh no se encuentra en ejecución" "ERROR"
+	fi
 else
-	echo "============ [ERROR] No se puede invocar el comando ya que procesoSisOp.sh no se encuentra en ejecución ============"
-	./glog "stop" "No se pudo invocar el comando ya que procesoSisOp.sh no se encuentra en ejecución" "ERROR"
+	ps cax | grep "proceso.sh" > /dev/null
+
+	if [ $? -eq 0 ]; 
+	then
+		pkill "proceso.sh"
+		echo "============ [STOP] Se invoca el comando correctamente. Se aborta la ejecución de proceso.sh ============"
+		#./glog "stop" "Se invoca el comando correctamente. Se aborta la ejecución de proceso.sh"
+	else
+		echo "============ [STOP] [ERROR] No se puede invocar el comando ya que proceso.sh no se encuentra en ejecución ============"
+		#./glog "stop" "No se pudo invocar el comando ya que proceso.sh no se encuentra en ejecución" "ERROR"
+	fi
 fi
